# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import st
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import QMessageBox, QInputDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 300)
        MainWindow.setMaximumSize(QtCore.QSize(400, 300))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 155, 93))
        self.groupBox.setObjectName("groupBox")
        self.KeySR = QtWidgets.QLineEdit(self.groupBox)
        self.KeySR.setEnabled(True)
        self.KeySR.setGeometry(QtCore.QRect(10, 20, 133, 20))
        self.KeySR.setText("")
        self.KeySR.setEchoMode(QtWidgets.QLineEdit.Password)
        self.KeySR.setDragEnabled(True)
        self.KeySR.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.KeySR.setClearButtonEnabled(True)
        self.KeySR.setObjectName("KeySR")
        self.KeyYZ = QtWidgets.QPushButton(self.groupBox)
        self.KeyYZ.setEnabled(True)
        self.KeyYZ.setGeometry(QtCore.QRect(10, 50, 61, 23))
        self.KeyYZ.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.KeyYZ.setObjectName("KeyYZ")
        self.KeyGG = QtWidgets.QPushButton(self.groupBox)
        self.KeyGG.setEnabled(False)
        self.KeyGG.setGeometry(QtCore.QRect(104, 50, 41, 23))
        self.KeyGG.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.KeyGG.setObjectName("KeyGG")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 9, 171, 93))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setEnabled(True)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 62, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.SetS = QtWidgets.QSpinBox(self.layoutWidget)
        self.SetS.setEnabled(True)
        self.SetS.setObjectName("SetS")
        self.SetS.setMaximum(9999)
        self.horizontalLayout.addWidget(self.SetS)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setEnabled(True)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 62, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.SetMin = QtWidgets.QSpinBox(self.layoutWidget1)
        self.SetMin.setEnabled(True)
        self.SetMin.setObjectName("SetMin")
        self.horizontalLayout_2.addWidget(self.SetMin)
        self.SetMin.setMaximum(9999)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setEnabled(True)
        self.layoutWidget2.setGeometry(QtCore.QRect(80, 20, 62, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.SetH = QtWidgets.QSpinBox(self.layoutWidget2)
        self.SetH.setEnabled(True)
        self.SetH.setObjectName("SetDay")
        self.horizontalLayout_3.addWidget(self.SetH)
        self.SetH.setMaximum(9999)
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber.setEnabled(True)
        self.lcdNumber.setGeometry(QtCore.QRect(80, 50, 81, 23))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(9)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 110, 155, 83))
        self.groupBox_3.setObjectName("groupBox_3")
        self.CC = QtWidgets.QLineEdit(self.groupBox_3)
        self.CC.setEnabled(True)
        self.CC.setGeometry(QtCore.QRect(10, 20, 133, 20))
        self.CC.setText("")
        self.CC.setMaxLength(512)
        self.CC.setDragEnabled(False)
        self.CC.setClearButtonEnabled(True)
        self.CC.setObjectName("CC")
        self.Cbj = QtWidgets.QPushButton(self.groupBox_3)
        self.Cbj.setEnabled(True)
        self.Cbj.setGeometry(QtCore.QRect(90, 50, 51, 23))
        self.Cbj.setObjectName("Cbj")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(190, 110, 146, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget3.setEnabled(True)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 126, 46))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioCQGJ = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioCQGJ.setEnabled(True)
        self.radioCQGJ.setObjectName("radioCQGJ")
        self.gridLayout.addWidget(self.radioCQGJ, 0, 1, 1, 1)
        self.radioCQ = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioCQ.setEnabled(True)
        self.radioCQ.setObjectName("radioCQ")
        self.gridLayout.addWidget(self.radioCQ, 1, 0, 1, 1)
        self.radioGJ = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioGJ.setEnabled(True)
        self.radioGJ.setObjectName("radioGJ")
        self.gridLayout.addWidget(self.radioGJ, 0, 0, 1, 1)
        self.radioGJQD = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioGJQD.setEnabled(True)
        self.radioGJQD.setObjectName("radioGJQD")
        self.gridLayout.addWidget(self.radioGJQD, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setEnabled(False)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 200, 95, 93))
        self.groupBox_5.setObjectName("groupBox_5")
        self.GB = QtWidgets.QPushButton(self.groupBox_5)
        self.GB.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.GB.setObjectName("GB")
        self.QX = QtWidgets.QPushButton(self.groupBox_5)
        self.QX.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.QX.setObjectName("QX")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 260, 75, 23))
        self.pushButton_4.setAutoDefault(True)
        self.pushButton_4.setDefault(True)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        # 我才不会告诉你，这是下次更新的内容，是预览时间
        '''self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setGeometry(QtCore.QRect(120, 200, 181, 91))
        self.groupBox_6.setObjectName("groupBox_6")'''
        '''self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 54, 21))
        self.label_4.setObjectName("label_4")'''
        '''self.tim = QtWidgets.QLineEdit(self.groupBox_6)
        self.tim.setGeometry(QtCore.QRect(60, 20, 111, 20))
        self.tim.setReadOnly(True)
        self.tim.setObjectName("tim")'''
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_4.clicked.connect(self.about)
        self.KeyYZ.clicked.connect(self.verification)
        self.Cbj.clicked.connect(self.Edit_Comment)
        self.KeyGG.clicked.connect(self.Change_key)
        self.QX.clicked.connect(self.canceler)
        self.GB.clicked.connect(self.Shutdown)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 计时器 # 系LCD数字显示
        self.timerA = QTimer(MainWindow)

        self.timerA.timeout.connect(self.TIME)

    def Shutdown(self):
        C错误 = False
        C超前时间 = self.lcdNumber.value()
        Z注释 = self.CC.text()

        ok = QMessageBox.question(MainWindow, '问题', '确定吗？', QMessageBox.Yes | QMessageBox.No)
        if ok == QMessageBox.No:
            C错误 = True

        if C超前时间 == 0.0:
            ko = QMessageBox.question(MainWindow, '问题', '超前时间为0秒\n会马上关闭，确定吗？', QMessageBox.Yes | QMessageBox.No)
            if ko == QMessageBox.No:
                C错误 = True

        if self.radioGJ.isChecked():
            CMD执行 = '-s'

        if self.radioCQ.isChecked():
            CMD执行 = '-r'

        if self.radioCQGJ.isChecked():
            CMD执行 = '-r -o'

        if self.radioGJQD.isChecked():
            CMD执行 = '-s -fw'

        try:
            print(CMD执行)
        except UnboundLocalError:
            QMessageBox.critical(MainWindow, '关键性终止', '没有设置执行任务')
            C错误 = True

        print(Z注释)

        if Z注释 == '':
            CMD注释 = ''
        else:
            CMD注释 = '-c ' + Z注释

        C超前时间 = int(C超前时间)

        if not C错误:
            print('Shutdown ' + CMD执行 + ' ' + '-t ' + str(C超前时间) + '' + CMD注释)
            os.system('Shutdown ' + CMD执行 + ' ' + '-t ' + str(C超前时间) + ' ' + CMD注释)

    def TIME(self):
        秒 = self.SetS.value()
        分 = self.SetMin.value()
        时 = self.SetH.value()

        秒 = 秒 + 分 * 60 + 时 * 60 * 60

        self.lcdNumber.setProperty('value', 秒)
        self.lcdNumber.setProperty('value', 秒)

    def canceler(self):  # 取消关闭
        os.system('Shutdown -a')
        QMessageBox.information(MainWindow, '信息', '已经取消当前关闭\n(如果可能)')

    def Change_key(self):  # 更改密钥
        ok = QMessageBox.question(MainWindow, '提问', '确认更改?', QMessageBox.Yes | QMessageBox.No)
        if ok == QMessageBox.Yes:
            text, ok = QInputDialog.getText(MainWindow, '设置', '设置新的 key\n请不要输入中文因为无法输入\n保留字"None_"等于空')
            if ok:
                s = '''[PW]
password:''' + text
                setting = open('setting.ini', 'w', encoding='utf-8')
                setting.write(s)
                setting.close()

    def Edit_Comment(self):  # 注释窗口
        text, ok = QInputDialog.getText(MainWindow, '注释', '设置注释', )
        if ok:
            self.CC.setText(text)

    def about(self):  # 关于
        QMessageBox.about(MainWindow, '关于', '作者:𝓒𝓸𝓸𝓵 𝓖𝓾𝓪𝓷𝓰𝓴𝓾𝓷\n版本:1.2\n提出的建议请在 liang2457@qq.com \n邮箱上诉说')

    def verification(self):  # 验证key
        key = self.KeySR.text()
        password = st.setting()
        _wz = password.find('password')
        password = password[_wz:]
        password = password.partition(':')
        password = password[2:]
        password = str(password)
        password = password[2:-3]

        if password == 'None_':
            password = ''

        if not key == password:
            QMessageBox.critical(MainWindow, '错误', '验证错误')
        else:
            self.KeyGG.setEnabled(True)
            self.GB.setEnabled(True)
            self.QX.setEnabled(True)
            self.groupBox_5.setEnabled(True)
            self.KeyYZ.setEnabled(False)
            self.KeySR.setText('')
            self.KeySR.setPlaceholderText('验证正确')
            self.KeySR.setEnabled(False)
            self.timerA.start(100)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "定时关机"))
        self.groupBox.setTitle(_translate("MainWindow", "key"))
        self.KeySR.setPlaceholderText(_translate("MainWindow", "请输入 key 继续"))
        self.KeyYZ.setText(_translate("MainWindow", "验证"))
        self.KeyGG.setText(_translate("MainWindow", "更改"))
        self.groupBox_2.setTitle(_translate("MainWindow", "时间设置"))
        self.label.setText(_translate("MainWindow", "秒"))
        self.label_2.setText(_translate("MainWindow", "分"))
        self.label_3.setText(_translate("MainWindow", "时"))
        self.groupBox_3.setTitle(_translate("MainWindow", "注释"))
        self.CC.setPlaceholderText(_translate("MainWindow", "有关关机/重启的注释"))
        self.Cbj.setText(_translate("MainWindow", "编辑"))
        self.groupBox_4.setTitle(_translate("MainWindow", "执行"))
        self.radioCQGJ.setText(_translate("MainWindow", "启动固件"))
        self.radioCQ.setText(_translate("MainWindow", "重启"))
        self.radioGJ.setText(_translate("MainWindow", "关机"))
        self.radioGJQD.setText(_translate("MainWindow", "高级启动"))
        self.groupBox_5.setTitle(_translate("MainWindow", "确认"))
        self.GB.setText(_translate("MainWindow", "关闭"))
        self.QX.setText(_translate("MainWindow", "取消"))
        self.pushButton_4.setText(_translate("MainWindow", "关于"))


if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
